title: <p align="centre"> Umesh Wagharalkar </p>
logo: /assets/img/Umesh Pic.JPG
description:   
<p align="center"> I'm working on Data Science, Big Data, Machine learning & NLP related problems. 
Worked with Teleperformance, Kotak bank for Data Analytics team. Working for Capgemini Technologies - Automation, Bigdata domain since a year.
</p>





theme: jekyll-theme-minimal
